/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "projet.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct AbonnementCompte *
ajoutercompte_1(struct AbonnementCompte *argp, CLIENT *clnt)
{
	static struct AbonnementCompte clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ajouterCompte,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) argp,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct AbonnementCompte *
supprimercompte_1(struct AbonnementCompte *argp, CLIENT *clnt)
{
	static struct AbonnementCompte clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, supprimerCompte,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) argp,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct AbonnementCompte *
resilierabonnement_1(struct AbonnementCompte *argp, CLIENT *clnt)
{
	static struct AbonnementCompte clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, resilierAbonnement,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) argp,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct AbonnementCompte *
ajoutersolde_1(struct AjoutSoldeParams *argp, CLIENT *clnt)
{
	static struct AbonnementCompte clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ajouterSolde,
		(xdrproc_t) xdr_AjoutSoldeParams, (caddr_t) argp,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
affichercompte_1(struct AbonnementCompte *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, afficherCompte,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
afficherabonnement_1(struct AbonnementCompte *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, afficherAbonnement,
		(xdrproc_t) xdr_AbonnementCompte, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}
