/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "projet.h"

bool_t
xdr_Compte (XDR *xdrs, Compte *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mail, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->paysResidence, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->solde))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Abonnement (XDR *xdrs, Abonnement *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->service, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbPlaces))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->typePartage, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->typePaiement, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AjoutSoldeParams (XDR *xdrs, AjoutSoldeParams *objp)
{
	register int32_t *buf;

	 if (!xdr_AbonnementCompte (xdrs, &objp->compte))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->montant))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AbonnementCompte (XDR *xdrs, AbonnementCompte *objp)
{
	register int32_t *buf;

	 if (!xdr_Compte (xdrs, &objp->compte))
		 return FALSE;
	 if (!xdr_Abonnement (xdrs, &objp->abonnement))
		 return FALSE;
	return TRUE;
}
