/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROJET_H_RPCGEN
#define _PROJET_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Compte {
	char nom[10];
	char prenom[20];
	char mail[30];
	char paysResidence[20];
	float solde;
};
typedef struct Compte Compte;

struct Abonnement {
	char service[20];
	int prix;
	int nbPlaces;
	char typePartage[15];
	char typePaiement[15];
};
typedef struct Abonnement Abonnement;

struct AjoutSoldeParams {
	struct AbonnementCompte compte;
	float montant;
};
typedef struct AjoutSoldeParams AjoutSoldeParams;

struct AbonnementCompte {
	struct Compte compte;
	struct Abonnement abonnement;
};
typedef struct AbonnementCompte AbonnementCompte;

#define GESTION_COMPTE 0x20000001
#define GESTION_COMPTE_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ajouterCompte 1
extern  struct AbonnementCompte * ajoutercompte_1(struct AbonnementCompte *, CLIENT *);
extern  struct AbonnementCompte * ajoutercompte_1_svc(struct AbonnementCompte *, struct svc_req *);
#define supprimerCompte 2
extern  struct AbonnementCompte * supprimercompte_1(struct AbonnementCompte *, CLIENT *);
extern  struct AbonnementCompte * supprimercompte_1_svc(struct AbonnementCompte *, struct svc_req *);
#define resilierAbonnement 3
extern  struct AbonnementCompte * resilierabonnement_1(struct AbonnementCompte *, CLIENT *);
extern  struct AbonnementCompte * resilierabonnement_1_svc(struct AbonnementCompte *, struct svc_req *);
#define ajouterSolde 4
extern  struct AbonnementCompte * ajoutersolde_1(struct AjoutSoldeParams *, CLIENT *);
extern  struct AbonnementCompte * ajoutersolde_1_svc(struct AjoutSoldeParams *, struct svc_req *);
#define afficherCompte 5
extern  void * affichercompte_1(struct AbonnementCompte *, CLIENT *);
extern  void * affichercompte_1_svc(struct AbonnementCompte *, struct svc_req *);
#define afficherAbonnement 6
extern  void * afficherabonnement_1(struct AbonnementCompte *, CLIENT *);
extern  void * afficherabonnement_1_svc(struct AbonnementCompte *, struct svc_req *);
extern int gestion_compte_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ajouterCompte 1
extern  struct AbonnementCompte * ajoutercompte_1();
extern  struct AbonnementCompte * ajoutercompte_1_svc();
#define supprimerCompte 2
extern  struct AbonnementCompte * supprimercompte_1();
extern  struct AbonnementCompte * supprimercompte_1_svc();
#define resilierAbonnement 3
extern  struct AbonnementCompte * resilierabonnement_1();
extern  struct AbonnementCompte * resilierabonnement_1_svc();
#define ajouterSolde 4
extern  struct AbonnementCompte * ajoutersolde_1();
extern  struct AbonnementCompte * ajoutersolde_1_svc();
#define afficherCompte 5
extern  void * affichercompte_1();
extern  void * affichercompte_1_svc();
#define afficherAbonnement 6
extern  void * afficherabonnement_1();
extern  void * afficherabonnement_1_svc();
extern int gestion_compte_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Compte (XDR *, Compte*);
extern  bool_t xdr_Abonnement (XDR *, Abonnement*);
extern  bool_t xdr_AjoutSoldeParams (XDR *, AjoutSoldeParams*);
extern  bool_t xdr_AbonnementCompte (XDR *, AbonnementCompte*);

#else /* K&R C */
extern bool_t xdr_Compte ();
extern bool_t xdr_Abonnement ();
extern bool_t xdr_AjoutSoldeParams ();
extern bool_t xdr_AbonnementCompte ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROJET_H_RPCGEN */
